name: Pre-Releaase

# Trigger
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Checkout Secret
      uses: actions/checkout@v3
      with:
        repository: ${{ secrets.SECRET_REPO }}
        token: ${{ secrets.TOKEN }}                     # Repo token
        path: secret
    # Prepare secret files
    - name: Copy Secret Files
      run: |
        cd secret/Blenh
        cp key.jks ../..
        cp secret.gradle.kts ../..
    # Clean secret files
    - name: Clean Temp Secret Files
      run: |
        rm -rf ./secret
    # Build
    - name: Build with Gradle
      run: |
        bash ./gradlew assembleGitHubRelease
    # Upload apk (arm64-v8a)
    - name: Upload Pre-Release Apk (arm64-v8a)
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Apk (arm64-v8a)
        path: app/build/outputs/apk/GitHub/release/*arm64-v8a*.apk
    # Upload apk (armeabi-v7a)
    - name: Upload Pre-Release Apk (armeabi-v7a)
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Apk (armeabi-v7a)
        path: app/build/outputs/apk/GitHub/release/*armeabi-v7a*.apk
    # Upload apk (x86_64)
    - name: Upload Pre-Release Apk (x86_64)
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Apk (x86_64)
        path: app/build/outputs/apk/GitHub/release/*x86_64*.apk
    # Upload apk (x86)
    - name: Upload Pre-Release Apk (x86)
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Apk (x86)
        path: |
          app/build/outputs/apk/GitHub/release/*x86*.apk
          !app/build/outputs/apk/GitHub/release/*x86_64*.apk
    # Upload apk (universal)
    - name: Upload Pre-Release Apk (universal)
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Apk (universal)
        path: app/build/outputs/apk/GitHub/release/*universal*.apk
    # Upload mapping
    - name: Upload Pre-Release Mapping
      uses: actions/upload-artifact@v3
      with:
        name: Pre-Release Mapping
        path: app/build/outputs/mapping/GitHubRelease/mapping.txt